### ISSUE TITLE
Left floated elements break layout

### ISSUE THREAD

**Issue by CamilleScholtz** [egilll/tex-linebreak2#5]
Floated elements on the leftinsert a `<br>` tag after every word, whereas floated elements on the right seem to work well:

<img width="774" alt="image" src="https://user-images.githubusercontent.com/5213535/218343681-e684ab99-6c35-408a-a0c0-ebd297c7170b.png">

<img width="724" alt="image" src="https://user-images.githubusercontent.com/5213535/218343699-61b0a85b-2f65-4c5f-a878-0a5a851bd180.png">

**Comment by egilll** [comment]
Fixed, thank you

**Comment by CamilleScholtz** [comment]
Thanks!
