### ISSUE TITLE
Can dependency on core-js (15MB) be removed?

### ISSUE THREAD

**Issue by james-hu** [egilll/tex-linebreak2#6]
First of all, thank you for creating this package.

I realised that the package has a dependency on core-js which is huge (15MB).
I searched in the code, it seems to be used in only these two lines in src/index.ts for polyfilling the "at" function:

```
import "core-js/stable/array/at";
...
    if (this.endsWithSoftHyphen && this.items.at(-2)?.type === "glue") {
...
    return isSoftHyphen(this.items.at(-1));
```

Would it be better if dependency on core-js is removed?

Background: I am trying to use the package in an AWS Lambda function, additional huge depdency made the bundle size exceeds AWS's limit.

**Comment by egilll** [comment]
Done ✅
